name: CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux

    steps:
      - name: Install build dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm base-devel ghc git zip haskell-shake libime

      - name: Fetch source code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build
        run: |
          export LANG=C.UTF-8
          runghc ./Main.hs -j build

      - uses: "softprops/action-gh-release@v2"
        with:
          prerelease: true
          files: |
            build/*.zip
